[phases.setup]
nixPkgs = ["bun", "nodejs_22"]
includeNode = false

[phases.build]
cmds = ["bun install", "bunx prisma migrate deploy", "bunx prisma generate", "bun run build"]

[start]
cmd = "bun start"
